@startuml
skinparam backgroundColor #F9F9F9
skinparam actorBackgroundColor #8CBDF5
skinparam usecaseBackgroundColor #FFFFFF
skinparam usecaseBorderColor #01579B

top to bottom direction

actor "Analista de Talento Humano" as ActorAnalista
actor "Postulante" as ActorPostulante

rectangle "Sistema de Contratación de Talento Humano" as Sistema {
package "<<module>> \n Módulo - Evaluación" as Módulo {

  usecase "Notificar avance de fase\na postulantes" as UC03
  usecase "Preparar notificación" as UCGeneralizar
  usecase "Verificar elegibilidad\ncandidatos" as UC03_1
  usecase "Registrar estado de entrega\nen sistema" as UC03_4
  usecase "Enviar correo a\npostulantes" as UC03_3

}
}

'' Relaciones principales
ActorAnalista --> UC03 : "Configura y lanza la notificación"
UC03 --> UCGeneralizar : <<include>>
UCGeneralizar <|-- UC03_1
UCGeneralizar <|-- UC03_2
UCGeneralizar <|-- UC03_4

UC03 --> UC03_3 : <<include>>

'' Recepción del resultado final
ActorPostulante <-- UC03_3 : "Recibe mensaje o correo electrónico"

@enduml